// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: yysystem.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - yysystem.YYSpeech

/// Namespace containing generated types for the "yysystem.YYSpeech" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum Yysystem_YYSpeech {
    /// Service descriptor for the "yysystem.YYSpeech" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "yysystem.YYSpeech")
    /// Namespace for method metadata.
    public enum Method {
        /// Namespace for "RecognizeStream" metadata.
        public enum RecognizeStream {
            /// Request type for "RecognizeStream".
            public typealias Input = Yysystem_StreamRequest
            /// Response type for "RecognizeStream".
            public typealias Output = Yysystem_StreamResponse
            /// Descriptor for "RecognizeStream".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "yysystem.YYSpeech"),
                method: "RecognizeStream"
            )
        }
        /// Descriptors for all methods in the "yysystem.YYSpeech" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            RecognizeStream.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "yysystem.YYSpeech" service.
    public static let yysystem_YYSpeech = GRPCCore.ServiceDescriptor(fullyQualifiedService: "yysystem.YYSpeech")
}

// MARK: yysystem.YYSpeech (server)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Yysystem_YYSpeech {
    /// Streaming variant of the service protocol for the "yysystem.YYSpeech" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > 音声認識サービス
    public protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "RecognizeStream" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > 双方向ストリーミング音声認識
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Yysystem_StreamRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Yysystem_StreamResponse` messages.
        func recognizeStream(
            request: GRPCCore.StreamingServerRequest<Yysystem_StreamRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Yysystem_StreamResponse>
    }

    /// Service protocol for the "yysystem.YYSpeech" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > 音声認識サービス
    public protocol ServiceProtocol: Yysystem_YYSpeech.StreamingServiceProtocol {
        /// Handle the "RecognizeStream" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > 双方向ストリーミング音声認識
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Yysystem_StreamRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Yysystem_StreamResponse` messages.
        func recognizeStream(
            request: GRPCCore.StreamingServerRequest<Yysystem_StreamRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Yysystem_StreamResponse>
    }

    /// Simple service protocol for the "yysystem.YYSpeech" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > 音声認識サービス
    public protocol SimpleServiceProtocol: Yysystem_YYSpeech.ServiceProtocol {
        /// Handle the "RecognizeStream" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > 双方向ストリーミング音声認識
        ///
        /// - Parameters:
        ///   - request: A stream of `Yysystem_StreamRequest` messages.
        ///   - response: A response stream of `Yysystem_StreamResponse` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        func recognizeStream(
            request: GRPCCore.RPCAsyncSequence<Yysystem_StreamRequest, any Swift.Error>,
            response: GRPCCore.RPCWriter<Yysystem_StreamResponse>,
            context: GRPCCore.ServerContext
        ) async throws
    }
}

// Default implementation of 'registerMethods(with:)'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Yysystem_YYSpeech.StreamingServiceProtocol {
    public func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: Yysystem_YYSpeech.Method.RecognizeStream.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Yysystem_StreamRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Yysystem_StreamResponse>(),
            handler: { request, context in
                try await self.recognizeStream(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Yysystem_YYSpeech.ServiceProtocol {
}

// Default implementation of methods from 'ServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Yysystem_YYSpeech.SimpleServiceProtocol {
    public func recognizeStream(
        request: GRPCCore.StreamingServerRequest<Yysystem_StreamRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Yysystem_StreamResponse> {
        return GRPCCore.StreamingServerResponse<Yysystem_StreamResponse>(
            metadata: [:],
            producer: { writer in
                try await self.recognizeStream(
                    request: request.messages,
                    response: writer,
                    context: context
                )
                return [:]
            }
        )
    }
}

// MARK: yysystem.YYSpeech (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Yysystem_YYSpeech {
    /// Generated client protocol for the "yysystem.YYSpeech" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > 音声認識サービス
    public protocol ClientProtocol: Sendable {
        /// Call the "RecognizeStream" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > 双方向ストリーミング音声認識
        ///
        /// - Parameters:
        ///   - request: A streaming request producing `Yysystem_StreamRequest` messages.
        ///   - serializer: A serializer for `Yysystem_StreamRequest` messages.
        ///   - deserializer: A deserializer for `Yysystem_StreamResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func recognizeStream<Result>(
            request: GRPCCore.StreamingClientRequest<Yysystem_StreamRequest>,
            serializer: some GRPCCore.MessageSerializer<Yysystem_StreamRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Yysystem_StreamResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Yysystem_StreamResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "yysystem.YYSpeech" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > 音声認識サービス
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "RecognizeStream" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > 双方向ストリーミング音声認識
        ///
        /// - Parameters:
        ///   - request: A streaming request producing `Yysystem_StreamRequest` messages.
        ///   - serializer: A serializer for `Yysystem_StreamRequest` messages.
        ///   - deserializer: A deserializer for `Yysystem_StreamResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func recognizeStream<Result>(
            request: GRPCCore.StreamingClientRequest<Yysystem_StreamRequest>,
            serializer: some GRPCCore.MessageSerializer<Yysystem_StreamRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Yysystem_StreamResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Yysystem_StreamResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable {
            try await self.client.bidirectionalStreaming(
                request: request,
                descriptor: Yysystem_YYSpeech.Method.RecognizeStream.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Yysystem_YYSpeech.ClientProtocol {
    /// Call the "RecognizeStream" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > 双方向ストリーミング音声認識
    ///
    /// - Parameters:
    ///   - request: A streaming request producing `Yysystem_StreamRequest` messages.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func recognizeStream<Result>(
        request: GRPCCore.StreamingClientRequest<Yysystem_StreamRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Yysystem_StreamResponse>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        try await self.recognizeStream(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Yysystem_StreamRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Yysystem_StreamResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Yysystem_YYSpeech.ClientProtocol {
    /// Call the "RecognizeStream" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > 双方向ストリーミング音声認識
    ///
    /// - Parameters:
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - producer: A closure producing request messages to send to the server. The request
    ///       stream is closed when the closure returns.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func recognizeStream<Result>(
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        requestProducer producer: @Sendable @escaping (GRPCCore.RPCWriter<Yysystem_StreamRequest>) async throws -> Void,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Yysystem_StreamResponse>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.StreamingClientRequest<Yysystem_StreamRequest>(
            metadata: metadata,
            producer: producer
        )
        return try await self.recognizeStream(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}