// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: yysystem.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// イベントタイプ
public nonisolated enum Yysystem_YYSpeechEventType: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int

  /// プロトファイルのバージョンの不一致がある場合に返されることがある
  case unknown // = 0

  /// セッション継続可能なエラーレスポンス
  case error // = 1

  /// 音声認識結果のレスポンス
  case speechRecognized // = 2

  /// [deprecated] 短文切り出し結果
  case textShortened // = 3

  /// テキスト修正結果
  case textRevised // = 4

  /// 翻訳結果
  case textTranslated // = 5
  case UNRECOGNIZED(Int)

  public init() {
    self = .unknown
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unknown
    case 1: self = .error
    case 2: self = .speechRecognized
    case 3: self = .textShortened
    case 4: self = .textRevised
    case 5: self = .textTranslated
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unknown: return 0
    case .error: return 1
    case .speechRecognized: return 2
    case .textShortened: return 3
    case .textRevised: return 4
    case .textTranslated: return 5
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Yysystem_YYSpeechEventType] = [
    .unknown,
    .error,
    .speechRecognized,
    .textShortened,
    .textRevised,
    .textTranslated,
  ]

}

/// ステータス
public nonisolated struct Yysystem_Status: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  ///  コード
  public var code: Int32 = 0

  /// メッセージ
  public var message: String = String()

  /// 詳細
  public var details: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// [not implemented] ルビ情報
public nonisolated struct Yysystem_RubyInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 開始地点
  /// transcriptの1文字目を0として何文字目から始まるかを示す値
  public var startIndex: Int32 = 0

  /// 終了地点
  /// transcriptの1文字目を0として何文字目で終わるかを示す値
  public var endIndex: Int32 = 0

  /// transcriptに含まれているルビを振る単語
  public var rb: String = String()

  /// rbの読み
  public var rt: String = String()

  /// rbの発音
  public var pronunciation: String = String()

  /// 読みが複数ある場合に格納される読みの配列
  public var otherReadings: [String] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// 単語情報
public nonisolated struct Yysystem_WordInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 開始時間[ms]
  public var startTime: Double = 0

  /// 終了時間[ms]
  public var endTime: Double = 0

  /// 単語
  public var word: String = String()

  /// 読み
  public var reading: String = String()

  /// 品詞
  public var partOfSpeech: String = String()

  /// 発音
  public var pronunciation: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// 辞書
public nonisolated struct Yysystem_Dictionary: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 単語
  public var word: String = String()

  /// 読み
  /// oneline: 読み reading
  ///辞書が適用される読みを指定します。 読み辞書を使う場合は ひらがな を使います。文字列置換辞書を使う場合は [] で囲います。 正規表現検索置換辞書を使う場合は [pattern]>[search_word] の形式で指定します。 例. ばなな [葡萄] [(?<=漢字の)リンゴ]>[リンゴ]
  public var reading: String = String()

  /// 無効化
  /// true: この辞書を無効化して辞書を適用しない
  /// false: 無効化しない。デフォルト値
  public var disabled: Bool = false

  /// 辞書タイプ DictionaryContextのタイプよりも優先される
  public var type: String = String()

  /// パターン
  /// string_search_replacement: 辞書が適用される文字列を指定
  /// regex_replacement, regex_search_replacement: 辞書が適用される正規表現パターンを指定
  public var pattern: String = String()

  /// regex_search_replacement: paternの正規表現にマッチした文字列から、ここで指定した文字列を検索して置換
  public var searchWord: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// セッション辞書
public nonisolated struct Yysystem_DictionaryContext: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 辞書
  /// Dictionary配列
  public var dictionaries: [Yysystem_Dictionary] = []

  /// 辞書タイプ
  /// readings, string_replacement, regex_replacement, regex_search_replacement のいずれか1つ
  public var type: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// フレーズ
public nonisolated struct Yysystem_Phrase: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// フレーズの値
  /// 例: "医道"
  public var value: String = String()

  /// [not implemented] ブースト値
  public var boost: Float = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// フレーズコンテキスト
public nonisolated struct Yysystem_PhraseContext: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// フレーズリスト
  /// 優先的に表示したい語句（フレーズ）のリスト
  public var phrases: [Yysystem_Phrase] = []

  /// [not implemented] ブースト値
  public var boost: Float = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// RecognizeStreamの設定値
public nonisolated struct Yysystem_StreamingConfig: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 音声データのエンコード
  /// デフォルト値: LINEAR16
  /// LINEAR16: 16ビットリニアPCM
  public var encoding: String {
    get {_storage._encoding ?? String()}
    set {_uniqueStorage()._encoding = newValue}
  }
  /// Returns true if `encoding` has been explicitly set.
  public var hasEncoding: Bool {_storage._encoding != nil}
  /// Clears the value of `encoding`. Subsequent reads from it will return its default value.
  public mutating func clearEncoding() {_uniqueStorage()._encoding = nil}

  /// 音声データのサンプリングレート
  /// デフォルト直: 16000
  public var sampleRateHertz: Int32 {
    get {_storage._sampleRateHertz ?? 0}
    set {_uniqueStorage()._sampleRateHertz = newValue}
  }
  /// Returns true if `sampleRateHertz` has been explicitly set.
  public var hasSampleRateHertz: Bool {_storage._sampleRateHertz != nil}
  /// Clears the value of `sampleRateHertz`. Subsequent reads from it will return its default value.
  public mutating func clearSampleRateHertz() {_uniqueStorage()._sampleRateHertz = nil}

  /// 言語コード
  /// デフォルト値: 4
  /// language_codeの項を参照
  public var languageCode: Int32 {
    get {_storage._languageCode ?? 0}
    set {_uniqueStorage()._languageCode = newValue}
  }
  /// Returns true if `languageCode` has been explicitly set.
  public var hasLanguageCode: Bool {_storage._languageCode != nil}
  /// Clears the value of `languageCode`. Subsequent reads from it will return its default value.
  public mutating func clearLanguageCode() {_uniqueStorage()._languageCode = nil}

  /// 最終結果のレスポンスデータに単語情報を含める設定
  /// デフォルト値: false
  /// true：最終結果に単語情報を含める
  /// false：最終結果に単語情報を含めない
  public var enableWord: Bool {
    get {_storage._enableWord ?? false}
    set {_uniqueStorage()._enableWord = newValue}
  }
  /// Returns true if `enableWord` has been explicitly set.
  public var hasEnableWord: Bool {_storage._enableWord != nil}
  /// Clears the value of `enableWord`. Subsequent reads from it will return its default value.
  public mutating func clearEnableWord() {_uniqueStorage()._enableWord = nil}

  /// 音声認識モデル
  /// 10: 最新モデル
  /// 11: 会話モデル
  /// 1: 旧モデル
  public var model: Int32 {
    get {_storage._model ?? 0}
    set {_uniqueStorage()._model = newValue}
  }
  /// Returns true if `model` has been explicitly set.
  public var hasModel: Bool {_storage._model != nil}
  /// Clears the value of `model`. Subsequent reads from it will return its default value.
  public mutating func clearModel() {_uniqueStorage()._model = nil}

  /// 音声認識の途中結果を返す設定
  /// デフォルト値: false
  /// true：途中結果を返す
  /// false：途中結果を返さない
  public var enableInterimResults: Bool {
    get {_storage._enableInterimResults ?? false}
    set {_uniqueStorage()._enableInterimResults = newValue}
  }
  /// Returns true if `enableInterimResults` has been explicitly set.
  public var hasEnableInterimResults: Bool {_storage._enableInterimResults != nil}
  /// Clears the value of `enableInterimResults`. Subsequent reads from it will return its default value.
  public mutating func clearEnableInterimResults() {_uniqueStorage()._enableInterimResults = nil}

  /// [not implemented]
  /// 翻訳言語
  /// デフォルト値: [] 空配列
  public var translateTo: [String] {
    get {_storage._translateTo}
    set {_uniqueStorage()._translateTo = newValue}
  }

  /// [not implemented]
  /// レスポンスデータにルビ情報を含める設定
  /// デフォルト値: false
  /// true：最終結果にルビ情報を含める
  /// false：最終結果にルビ情報を含めない
  public var enableRuby: Bool {
    get {_storage._enableRuby ?? false}
    set {_uniqueStorage()._enableRuby = newValue}
  }
  /// Returns true if `enableRuby` has been explicitly set.
  public var hasEnableRuby: Bool {_storage._enableRuby != nil}
  /// Clears the value of `enableRuby`. Subsequent reads from it will return its default value.
  public mutating func clearEnableRuby() {_uniqueStorage()._enableRuby = nil}

  /// 音声データのチャンネル数
  /// デフォルト値: 1
  public var audioChannelCount: Int32 {
    get {_storage._audioChannelCount ?? 0}
    set {_uniqueStorage()._audioChannelCount = newValue}
  }
  /// Returns true if `audioChannelCount` has been explicitly set.
  public var hasAudioChannelCount: Bool {_storage._audioChannelCount != nil}
  /// Clears the value of `audioChannelCount`. Subsequent reads from it will return its default value.
  public mutating func clearAudioChannelCount() {_uniqueStorage()._audioChannelCount = nil}

  /// 最終けかを返す前の無音区間[ms]
  /// デフォルト値: 500
  /// 設定範囲: 100 - 2500
  /// model = 10, 11 の時のみ有効
  public var segmentationSilenceTimeoutMs: Int32 {
    get {_storage._segmentationSilenceTimeoutMs ?? 0}
    set {_uniqueStorage()._segmentationSilenceTimeoutMs = newValue}
  }
  /// Returns true if `segmentationSilenceTimeoutMs` has been explicitly set.
  public var hasSegmentationSilenceTimeoutMs: Bool {_storage._segmentationSilenceTimeoutMs != nil}
  /// Clears the value of `segmentationSilenceTimeoutMs`. Subsequent reads from it will return its default value.
  public mutating func clearSegmentationSilenceTimeoutMs() {_uniqueStorage()._segmentationSilenceTimeoutMs = nil}

  /// セッション辞書リスト
  /// デフォルト値: [] 空配列
  public var dictionaryContexts: [Yysystem_DictionaryContext] {
    get {_storage._dictionaryContexts}
    set {_uniqueStorage()._dictionaryContexts = newValue}
  }

  /// 優先語句リスト [] 空配列
  public var phraseContexts: [Yysystem_PhraseContext] {
    get {_storage._phraseContexts}
    set {_uniqueStorage()._phraseContexts = newValue}
  }

  /// 自動言語検出
  /// デフォルト値: なし
  /// model = 10, 11 の時のみ有効
  /// 例: 英語と日本語が話される可能性があるとき
  /// [1, 4]
  public var autoDetectLanguageCodes: [Int32] {
    get {_storage._autoDetectLanguageCodes}
    set {_uniqueStorage()._autoDetectLanguageCodes = newValue}
  }

  /// [not implemented]
  /// 翻訳のレスポンスを有効にする
  /// デフォルト値: true
  /// true：最終結果に翻訳結果を含める
  /// false：最終結果に翻訳結果を含めない
  /// translate_toが設定されている場合のみ機能する
  /// 翻訳結果のレスポンスは
  public var enableTranslation: Bool {
    get {_storage._enableTranslation ?? false}
    set {_uniqueStorage()._enableTranslation = newValue}
  }
  /// Returns true if `enableTranslation` has been explicitly set.
  public var hasEnableTranslation: Bool {_storage._enableTranslation != nil}
  /// Clears the value of `enableTranslation`. Subsequent reads from it will return its default value.
  public mutating func clearEnableTranslation() {_uniqueStorage()._enableTranslation = nil}

  /// [deprecated]
  /// 短文切り出し
  /// model = 10, 11 の時のみ有効
  /// language_code = 4 の時のみ有効
  /// デフォルト: false
  /// true：短文切り出しする
  /// false: 短文切り出ししない
  public var shortenTexts: Bool {
    get {_storage._shortenTexts ?? false}
    set {_uniqueStorage()._shortenTexts = newValue}
  }
  /// Returns true if `shortenTexts` has been explicitly set.
  public var hasShortenTexts: Bool {_storage._shortenTexts != nil}
  /// Clears the value of `shortenTexts`. Subsequent reads from it will return its default value.
  public mutating func clearShortenTexts() {_uniqueStorage()._shortenTexts = nil}

  /// テキスト修正のレスポンスを有効にする
  /// デフォルト値: false
  /// true：テキスト修正を有効にする
  /// false：テキスト修正を無効にする
  public var reviseTexts: Bool {
    get {_storage._reviseTexts ?? false}
    set {_uniqueStorage()._reviseTexts = newValue}
  }
  /// Returns true if `reviseTexts` has been explicitly set.
  public var hasReviseTexts: Bool {_storage._reviseTexts != nil}
  /// Clears the value of `reviseTexts`. Subsequent reads from it will return its default value.
  public mutating func clearReviseTexts() {_uniqueStorage()._reviseTexts = nil}

  /// 自動言語識別を有効にする
  /// auto_detect_language_codesが設定されている場合のみ機能する
  /// デフォルト値: true
  /// true：自動言語識別を有効にする
  /// false：自動言語識別を無効にする
  /// model = 10, 11 の時のみ有効
  public var enableAutoDetectLanguage: Bool {
    get {_storage._enableAutoDetectLanguage ?? false}
    set {_uniqueStorage()._enableAutoDetectLanguage = newValue}
  }
  /// Returns true if `enableAutoDetectLanguage` has been explicitly set.
  public var hasEnableAutoDetectLanguage: Bool {_storage._enableAutoDetectLanguage != nil}
  /// Clears the value of `enableAutoDetectLanguage`. Subsequent reads from it will return its default value.
  public mutating func clearEnableAutoDetectLanguage() {_uniqueStorage()._enableAutoDetectLanguage = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// RecognizeStreamのリクエストデータ
public nonisolated struct Yysystem_StreamRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// バッファサイズの推奨値 3200 〜 8192 bytes (encoding=LINEAR16, sample_rate_hertz =16000, audio_channel_count = 1の場合)
  /// リクエストの時間間隔を指定する必要がある場合は、100msを推奨します。
  /// （参考）ミリ秒[ms]とバッファサイズ[bytes]の関係式（LINEAR16の場合）
  /// <BUFFER_SIZE> [bytes] = 16 [bit (per frame)] / 8 [bit / bytes] * 16000 [Hz] / 1000 [ms / s] * <MILLI_SECONDS> [ms] * 1 [number of audio channels]
  public var audiobytes: Data = Data()

  /// ストリーミング設定値
  public var streamingConfig: Yysystem_StreamingConfig {
    get {_streamingConfig ?? Yysystem_StreamingConfig()}
    set {_streamingConfig = newValue}
  }
  /// Returns true if `streamingConfig` has been explicitly set.
  public var hasStreamingConfig: Bool {self._streamingConfig != nil}
  /// Clears the value of `streamingConfig`. Subsequent reads from it will return its default value.
  public mutating func clearStreamingConfig() {self._streamingConfig = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _streamingConfig: Yysystem_StreamingConfig? = nil
}

/// 翻訳結果
public nonisolated struct Yysystem_TranslationResult: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 翻訳先言語
  public var to: String = String()

  /// 翻訳結果
  public var text: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// [deprecated] 短縮テキスト詳細
public nonisolated struct Yysystem_ShortenTextsDetails: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// サーバーが追加した無音時間のバイトサイズ
  public var silenceByteSize: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// 音声認識結果
public nonisolated struct Yysystem_StreamResult: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 最終結果の判定
  /// true: 最終結果
  /// false: 途中結果
  public var isFinal: Bool = false

  /// 文字起こし結果
  public var transcript: String = String()

  /// 単語情報
  public var words: [Yysystem_WordInfo] = []

  /// 翻訳結果
  public var translations: [Yysystem_TranslationResult] = []

  /// [not implemented] ルビの情報
  public var rubies: [Yysystem_RubyInfo] = []

  /// [deprecated]
  /// 結果のID
  /// 途中結果と最終結果を紐づけるID
  public var resultID: String = String()

  /// 話者ID
  /// model = 11 の時のみ有効
  /// 例:
  /// Unknown, Guest-1, Guest-2, ...
  public var speakerID: String = String()

  /// 自動言語検出で識別された言語コード
  public var detectedLanguageCode: Int32 = 0

  /// [deprecated]
  /// 短文切り出しの詳細
  /// YYSpeechEventTypeがTEXT_SHORTENEDの場合のみ使用
  public var shortenTextsDetails: Yysystem_ShortenTextsDetails {
    get {_shortenTextsDetails ?? Yysystem_ShortenTextsDetails()}
    set {_shortenTextsDetails = newValue}
  }
  /// Returns true if `shortenTextsDetails` has been explicitly set.
  public var hasShortenTextsDetails: Bool {self._shortenTextsDetails != nil}
  /// Clears the value of `shortenTextsDetails`. Subsequent reads from it will return its default value.
  public mutating func clearShortenTextsDetails() {self._shortenTextsDetails = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _shortenTextsDetails: Yysystem_ShortenTextsDetails? = nil
}

/// RecognizeStreamのレスポンスデータ
public nonisolated struct Yysystem_StreamResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// エラー情報
  public var error: Yysystem_Status {
    get {_error ?? Yysystem_Status()}
    set {_error = newValue}
  }
  /// Returns true if `error` has been explicitly set.
  public var hasError: Bool {self._error != nil}
  /// Clears the value of `error`. Subsequent reads from it will return its default value.
  public mutating func clearError() {self._error = nil}

  /// 音声認識結果
  public var result: Yysystem_StreamResult {
    get {_result ?? Yysystem_StreamResult()}
    set {_result = newValue}
  }
  /// Returns true if `result` has been explicitly set.
  public var hasResult: Bool {self._result != nil}
  /// Clears the value of `result`. Subsequent reads from it will return its default value.
  public mutating func clearResult() {self._result = nil}

  /// [deprecated] ストリーミング設定値
  public var streamingConfig: Yysystem_StreamingConfig {
    get {_streamingConfig ?? Yysystem_StreamingConfig()}
    set {_streamingConfig = newValue}
  }
  /// Returns true if `streamingConfig` has been explicitly set.
  public var hasStreamingConfig: Bool {self._streamingConfig != nil}
  /// Clears the value of `streamingConfig`. Subsequent reads from it will return its default value.
  public mutating func clearStreamingConfig() {self._streamingConfig = nil}

  /// リクエストID gRPC接続時に生成されるユニークなID
  public var requestID: String = String()

  /// イベントタイプ
  public var eventType: Yysystem_YYSpeechEventType = .unknown

  /// 音声認識結果のID 最終結果ごとに更新されるユニークなID
  public var resultID: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _error: Yysystem_Status? = nil
  fileprivate var _result: Yysystem_StreamResult? = nil
  fileprivate var _streamingConfig: Yysystem_StreamingConfig? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "yysystem"

nonisolated extension Yysystem_YYSpeechEventType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0UNKNOWN\0\u{1}ERROR\0\u{1}SPEECH_RECOGNIZED\0\u{1}TEXT_SHORTENED\0\u{1}TEXT_REVISED\0\u{1}TEXT_TRANSLATED\0")
}

nonisolated extension Yysystem_Status: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Status"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}code\0\u{1}message\0\u{1}details\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.code) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.message) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.details) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.code != 0 {
      try visitor.visitSingularInt32Field(value: self.code, fieldNumber: 1)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 2)
    }
    if !self.details.isEmpty {
      try visitor.visitSingularStringField(value: self.details, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Yysystem_Status, rhs: Yysystem_Status) -> Bool {
    if lhs.code != rhs.code {return false}
    if lhs.message != rhs.message {return false}
    if lhs.details != rhs.details {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Yysystem_RubyInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RubyInfo"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}start_index\0\u{3}end_index\0\u{1}rb\0\u{1}rt\0\u{1}pronunciation\0\u{3}other_readings\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.startIndex) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.endIndex) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.rb) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.rt) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.pronunciation) }()
      case 6: try { try decoder.decodeRepeatedStringField(value: &self.otherReadings) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.startIndex != 0 {
      try visitor.visitSingularInt32Field(value: self.startIndex, fieldNumber: 1)
    }
    if self.endIndex != 0 {
      try visitor.visitSingularInt32Field(value: self.endIndex, fieldNumber: 2)
    }
    if !self.rb.isEmpty {
      try visitor.visitSingularStringField(value: self.rb, fieldNumber: 3)
    }
    if !self.rt.isEmpty {
      try visitor.visitSingularStringField(value: self.rt, fieldNumber: 4)
    }
    if !self.pronunciation.isEmpty {
      try visitor.visitSingularStringField(value: self.pronunciation, fieldNumber: 5)
    }
    if !self.otherReadings.isEmpty {
      try visitor.visitRepeatedStringField(value: self.otherReadings, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Yysystem_RubyInfo, rhs: Yysystem_RubyInfo) -> Bool {
    if lhs.startIndex != rhs.startIndex {return false}
    if lhs.endIndex != rhs.endIndex {return false}
    if lhs.rb != rhs.rb {return false}
    if lhs.rt != rhs.rt {return false}
    if lhs.pronunciation != rhs.pronunciation {return false}
    if lhs.otherReadings != rhs.otherReadings {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Yysystem_WordInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".WordInfo"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}start_time\0\u{3}end_time\0\u{1}word\0\u{1}reading\0\u{3}part_of_speech\0\u{1}pronunciation\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularDoubleField(value: &self.startTime) }()
      case 2: try { try decoder.decodeSingularDoubleField(value: &self.endTime) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.word) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.reading) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.partOfSpeech) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.pronunciation) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.startTime.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.startTime, fieldNumber: 1)
    }
    if self.endTime.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.endTime, fieldNumber: 2)
    }
    if !self.word.isEmpty {
      try visitor.visitSingularStringField(value: self.word, fieldNumber: 3)
    }
    if !self.reading.isEmpty {
      try visitor.visitSingularStringField(value: self.reading, fieldNumber: 4)
    }
    if !self.partOfSpeech.isEmpty {
      try visitor.visitSingularStringField(value: self.partOfSpeech, fieldNumber: 5)
    }
    if !self.pronunciation.isEmpty {
      try visitor.visitSingularStringField(value: self.pronunciation, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Yysystem_WordInfo, rhs: Yysystem_WordInfo) -> Bool {
    if lhs.startTime != rhs.startTime {return false}
    if lhs.endTime != rhs.endTime {return false}
    if lhs.word != rhs.word {return false}
    if lhs.reading != rhs.reading {return false}
    if lhs.partOfSpeech != rhs.partOfSpeech {return false}
    if lhs.pronunciation != rhs.pronunciation {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Yysystem_Dictionary: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Dictionary"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}word\0\u{1}reading\0\u{1}disabled\0\u{1}type\0\u{1}pattern\0\u{3}search_word\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.word) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.reading) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.disabled) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.type) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.pattern) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.searchWord) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.word.isEmpty {
      try visitor.visitSingularStringField(value: self.word, fieldNumber: 1)
    }
    if !self.reading.isEmpty {
      try visitor.visitSingularStringField(value: self.reading, fieldNumber: 2)
    }
    if self.disabled != false {
      try visitor.visitSingularBoolField(value: self.disabled, fieldNumber: 3)
    }
    if !self.type.isEmpty {
      try visitor.visitSingularStringField(value: self.type, fieldNumber: 4)
    }
    if !self.pattern.isEmpty {
      try visitor.visitSingularStringField(value: self.pattern, fieldNumber: 5)
    }
    if !self.searchWord.isEmpty {
      try visitor.visitSingularStringField(value: self.searchWord, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Yysystem_Dictionary, rhs: Yysystem_Dictionary) -> Bool {
    if lhs.word != rhs.word {return false}
    if lhs.reading != rhs.reading {return false}
    if lhs.disabled != rhs.disabled {return false}
    if lhs.type != rhs.type {return false}
    if lhs.pattern != rhs.pattern {return false}
    if lhs.searchWord != rhs.searchWord {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Yysystem_DictionaryContext: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DictionaryContext"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}dictionaries\0\u{1}type\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.dictionaries) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.type) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.dictionaries.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.dictionaries, fieldNumber: 1)
    }
    if !self.type.isEmpty {
      try visitor.visitSingularStringField(value: self.type, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Yysystem_DictionaryContext, rhs: Yysystem_DictionaryContext) -> Bool {
    if lhs.dictionaries != rhs.dictionaries {return false}
    if lhs.type != rhs.type {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Yysystem_Phrase: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Phrase"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}value\0\u{1}boost\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.value) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self.boost) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.value.isEmpty {
      try visitor.visitSingularStringField(value: self.value, fieldNumber: 1)
    }
    if self.boost.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.boost, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Yysystem_Phrase, rhs: Yysystem_Phrase) -> Bool {
    if lhs.value != rhs.value {return false}
    if lhs.boost != rhs.boost {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Yysystem_PhraseContext: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PhraseContext"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}phrases\0\u{1}boost\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.phrases) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self.boost) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.phrases.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.phrases, fieldNumber: 1)
    }
    if self.boost.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.boost, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Yysystem_PhraseContext, rhs: Yysystem_PhraseContext) -> Bool {
    if lhs.phrases != rhs.phrases {return false}
    if lhs.boost != rhs.boost {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Yysystem_StreamingConfig: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".StreamingConfig"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}encoding\0\u{3}sample_rate_hertz\0\u{3}language_code\0\u{3}enable_word\0\u{1}model\0\u{3}enable_interim_results\0\u{3}translate_to\0\u{3}enable_ruby\0\u{3}audio_channel_count\0\u{3}segmentation_silence_timeout_ms\0\u{3}dictionary_contexts\0\u{3}phrase_contexts\0\u{3}auto_detect_language_codes\0\u{3}enable_translation\0\u{3}shorten_texts\0\u{3}revise_texts\0\u{3}enable_auto_detect_language\0")

  fileprivate class _StorageClass {
    var _encoding: String? = nil
    var _sampleRateHertz: Int32? = nil
    var _languageCode: Int32? = nil
    var _enableWord: Bool? = nil
    var _model: Int32? = nil
    var _enableInterimResults: Bool? = nil
    var _translateTo: [String] = []
    var _enableRuby: Bool? = nil
    var _audioChannelCount: Int32? = nil
    var _segmentationSilenceTimeoutMs: Int32? = nil
    var _dictionaryContexts: [Yysystem_DictionaryContext] = []
    var _phraseContexts: [Yysystem_PhraseContext] = []
    var _autoDetectLanguageCodes: [Int32] = []
    var _enableTranslation: Bool? = nil
    var _shortenTexts: Bool? = nil
    var _reviseTexts: Bool? = nil
    var _enableAutoDetectLanguage: Bool? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _encoding = source._encoding
      _sampleRateHertz = source._sampleRateHertz
      _languageCode = source._languageCode
      _enableWord = source._enableWord
      _model = source._model
      _enableInterimResults = source._enableInterimResults
      _translateTo = source._translateTo
      _enableRuby = source._enableRuby
      _audioChannelCount = source._audioChannelCount
      _segmentationSilenceTimeoutMs = source._segmentationSilenceTimeoutMs
      _dictionaryContexts = source._dictionaryContexts
      _phraseContexts = source._phraseContexts
      _autoDetectLanguageCodes = source._autoDetectLanguageCodes
      _enableTranslation = source._enableTranslation
      _shortenTexts = source._shortenTexts
      _reviseTexts = source._reviseTexts
      _enableAutoDetectLanguage = source._enableAutoDetectLanguage
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularStringField(value: &_storage._encoding) }()
        case 2: try { try decoder.decodeSingularInt32Field(value: &_storage._sampleRateHertz) }()
        case 3: try { try decoder.decodeSingularInt32Field(value: &_storage._languageCode) }()
        case 4: try { try decoder.decodeSingularBoolField(value: &_storage._enableWord) }()
        case 5: try { try decoder.decodeSingularInt32Field(value: &_storage._model) }()
        case 6: try { try decoder.decodeSingularBoolField(value: &_storage._enableInterimResults) }()
        case 7: try { try decoder.decodeRepeatedStringField(value: &_storage._translateTo) }()
        case 8: try { try decoder.decodeSingularBoolField(value: &_storage._enableRuby) }()
        case 9: try { try decoder.decodeSingularInt32Field(value: &_storage._audioChannelCount) }()
        case 10: try { try decoder.decodeSingularInt32Field(value: &_storage._segmentationSilenceTimeoutMs) }()
        case 11: try { try decoder.decodeRepeatedMessageField(value: &_storage._dictionaryContexts) }()
        case 12: try { try decoder.decodeRepeatedMessageField(value: &_storage._phraseContexts) }()
        case 13: try { try decoder.decodeRepeatedInt32Field(value: &_storage._autoDetectLanguageCodes) }()
        case 14: try { try decoder.decodeSingularBoolField(value: &_storage._enableTranslation) }()
        case 15: try { try decoder.decodeSingularBoolField(value: &_storage._shortenTexts) }()
        case 16: try { try decoder.decodeSingularBoolField(value: &_storage._reviseTexts) }()
        case 17: try { try decoder.decodeSingularBoolField(value: &_storage._enableAutoDetectLanguage) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._encoding {
        try visitor.visitSingularStringField(value: v, fieldNumber: 1)
      } }()
      try { if let v = _storage._sampleRateHertz {
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 2)
      } }()
      try { if let v = _storage._languageCode {
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 3)
      } }()
      try { if let v = _storage._enableWord {
        try visitor.visitSingularBoolField(value: v, fieldNumber: 4)
      } }()
      try { if let v = _storage._model {
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 5)
      } }()
      try { if let v = _storage._enableInterimResults {
        try visitor.visitSingularBoolField(value: v, fieldNumber: 6)
      } }()
      if !_storage._translateTo.isEmpty {
        try visitor.visitRepeatedStringField(value: _storage._translateTo, fieldNumber: 7)
      }
      try { if let v = _storage._enableRuby {
        try visitor.visitSingularBoolField(value: v, fieldNumber: 8)
      } }()
      try { if let v = _storage._audioChannelCount {
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 9)
      } }()
      try { if let v = _storage._segmentationSilenceTimeoutMs {
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 10)
      } }()
      if !_storage._dictionaryContexts.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._dictionaryContexts, fieldNumber: 11)
      }
      if !_storage._phraseContexts.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._phraseContexts, fieldNumber: 12)
      }
      if !_storage._autoDetectLanguageCodes.isEmpty {
        try visitor.visitPackedInt32Field(value: _storage._autoDetectLanguageCodes, fieldNumber: 13)
      }
      try { if let v = _storage._enableTranslation {
        try visitor.visitSingularBoolField(value: v, fieldNumber: 14)
      } }()
      try { if let v = _storage._shortenTexts {
        try visitor.visitSingularBoolField(value: v, fieldNumber: 15)
      } }()
      try { if let v = _storage._reviseTexts {
        try visitor.visitSingularBoolField(value: v, fieldNumber: 16)
      } }()
      try { if let v = _storage._enableAutoDetectLanguage {
        try visitor.visitSingularBoolField(value: v, fieldNumber: 17)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Yysystem_StreamingConfig, rhs: Yysystem_StreamingConfig) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._encoding != rhs_storage._encoding {return false}
        if _storage._sampleRateHertz != rhs_storage._sampleRateHertz {return false}
        if _storage._languageCode != rhs_storage._languageCode {return false}
        if _storage._enableWord != rhs_storage._enableWord {return false}
        if _storage._model != rhs_storage._model {return false}
        if _storage._enableInterimResults != rhs_storage._enableInterimResults {return false}
        if _storage._translateTo != rhs_storage._translateTo {return false}
        if _storage._enableRuby != rhs_storage._enableRuby {return false}
        if _storage._audioChannelCount != rhs_storage._audioChannelCount {return false}
        if _storage._segmentationSilenceTimeoutMs != rhs_storage._segmentationSilenceTimeoutMs {return false}
        if _storage._dictionaryContexts != rhs_storage._dictionaryContexts {return false}
        if _storage._phraseContexts != rhs_storage._phraseContexts {return false}
        if _storage._autoDetectLanguageCodes != rhs_storage._autoDetectLanguageCodes {return false}
        if _storage._enableTranslation != rhs_storage._enableTranslation {return false}
        if _storage._shortenTexts != rhs_storage._shortenTexts {return false}
        if _storage._reviseTexts != rhs_storage._reviseTexts {return false}
        if _storage._enableAutoDetectLanguage != rhs_storage._enableAutoDetectLanguage {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Yysystem_StreamRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".StreamRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}audiobytes\0\u{3}streaming_config\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.audiobytes) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._streamingConfig) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.audiobytes.isEmpty {
      try visitor.visitSingularBytesField(value: self.audiobytes, fieldNumber: 1)
    }
    try { if let v = self._streamingConfig {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Yysystem_StreamRequest, rhs: Yysystem_StreamRequest) -> Bool {
    if lhs.audiobytes != rhs.audiobytes {return false}
    if lhs._streamingConfig != rhs._streamingConfig {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Yysystem_TranslationResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".TranslationResult"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}to\0\u{1}text\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.to) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.text) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.to.isEmpty {
      try visitor.visitSingularStringField(value: self.to, fieldNumber: 1)
    }
    if !self.text.isEmpty {
      try visitor.visitSingularStringField(value: self.text, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Yysystem_TranslationResult, rhs: Yysystem_TranslationResult) -> Bool {
    if lhs.to != rhs.to {return false}
    if lhs.text != rhs.text {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Yysystem_ShortenTextsDetails: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ShortenTextsDetails"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}silence_byte_size\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.silenceByteSize) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.silenceByteSize != 0 {
      try visitor.visitSingularInt32Field(value: self.silenceByteSize, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Yysystem_ShortenTextsDetails, rhs: Yysystem_ShortenTextsDetails) -> Bool {
    if lhs.silenceByteSize != rhs.silenceByteSize {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Yysystem_StreamResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".StreamResult"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}is_final\0\u{1}transcript\0\u{1}words\0\u{1}translations\0\u{1}rubies\0\u{3}result_id\0\u{3}speaker_id\0\u{3}detected_language_code\0\u{3}shorten_texts_details\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.isFinal) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.transcript) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.words) }()
      case 4: try { try decoder.decodeRepeatedMessageField(value: &self.translations) }()
      case 5: try { try decoder.decodeRepeatedMessageField(value: &self.rubies) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.resultID) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.speakerID) }()
      case 8: try { try decoder.decodeSingularInt32Field(value: &self.detectedLanguageCode) }()
      case 9: try { try decoder.decodeSingularMessageField(value: &self._shortenTextsDetails) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.isFinal != false {
      try visitor.visitSingularBoolField(value: self.isFinal, fieldNumber: 1)
    }
    if !self.transcript.isEmpty {
      try visitor.visitSingularStringField(value: self.transcript, fieldNumber: 2)
    }
    if !self.words.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.words, fieldNumber: 3)
    }
    if !self.translations.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.translations, fieldNumber: 4)
    }
    if !self.rubies.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.rubies, fieldNumber: 5)
    }
    if !self.resultID.isEmpty {
      try visitor.visitSingularStringField(value: self.resultID, fieldNumber: 6)
    }
    if !self.speakerID.isEmpty {
      try visitor.visitSingularStringField(value: self.speakerID, fieldNumber: 7)
    }
    if self.detectedLanguageCode != 0 {
      try visitor.visitSingularInt32Field(value: self.detectedLanguageCode, fieldNumber: 8)
    }
    try { if let v = self._shortenTextsDetails {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Yysystem_StreamResult, rhs: Yysystem_StreamResult) -> Bool {
    if lhs.isFinal != rhs.isFinal {return false}
    if lhs.transcript != rhs.transcript {return false}
    if lhs.words != rhs.words {return false}
    if lhs.translations != rhs.translations {return false}
    if lhs.rubies != rhs.rubies {return false}
    if lhs.resultID != rhs.resultID {return false}
    if lhs.speakerID != rhs.speakerID {return false}
    if lhs.detectedLanguageCode != rhs.detectedLanguageCode {return false}
    if lhs._shortenTextsDetails != rhs._shortenTextsDetails {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Yysystem_StreamResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".StreamResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}error\0\u{1}result\0\u{3}streaming_config\0\u{3}request_id\0\u{3}event_type\0\u{3}result_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._error) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._result) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._streamingConfig) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.requestID) }()
      case 5: try { try decoder.decodeSingularEnumField(value: &self.eventType) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.resultID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._error {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._result {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._streamingConfig {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    if !self.requestID.isEmpty {
      try visitor.visitSingularStringField(value: self.requestID, fieldNumber: 4)
    }
    if self.eventType != .unknown {
      try visitor.visitSingularEnumField(value: self.eventType, fieldNumber: 5)
    }
    if !self.resultID.isEmpty {
      try visitor.visitSingularStringField(value: self.resultID, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Yysystem_StreamResponse, rhs: Yysystem_StreamResponse) -> Bool {
    if lhs._error != rhs._error {return false}
    if lhs._result != rhs._result {return false}
    if lhs._streamingConfig != rhs._streamingConfig {return false}
    if lhs.requestID != rhs.requestID {return false}
    if lhs.eventType != rhs.eventType {return false}
    if lhs.resultID != rhs.resultID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
